/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cron-sync/wrangler.jsonc --include-runtime=false workers/cron-sync/worker-configuration.d.ts` (hash: fbc09122e968b0cff1e53f17d46c3d40)
interface __BaseEnv_Env {
	DB: D1Database;
	CRON_BATCH_SIZE: "1";
	VERIFIER_CONTAINER: DurableObjectNamespace<import("./src/index").OfficialLinkVerifier>;
	IMAGE_INGEST: Fetcher /* gamehub-image-ingest-production */ | Fetcher /* gamehub-image-ingest-cron-local */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OfficialLinkVerifier";
	}
	interface ProductionEnv {
		DB: D1Database;
		CRON_BATCH_SIZE: "1";
		VERIFIER_CONTAINER: DurableObjectNamespace<import("./src/index").OfficialLinkVerifier>;
		IMAGE_INGEST: Fetcher /* gamehub-image-ingest-production */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CRON_BATCH_SIZE">> {}
}
