import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { copyTrackedProductionInputs, isProductionBuildInput, productionBuildEnvironment } from "./production-build-inputs";
describe("publication gate production build inputs", () => {
  it.each(["app/page.tsx", "components/game/game-card.tsx", "lib/site-data/source.ts", "lib/site-data/serialize.ts", "public/favicon.ico", "scripts/check-site-data.ts", "package.json", "package-lock.json", "next.config.ts", "tsconfig.json", "postcss.config.mjs"])("allows tracked production input %s", (path) => expect(isProductionBuildInput(path, true)).toBe(true));
  it.each([["lib/mock-data.ts", true], ["lib/site-data/fixture-source.ts", true], ["lib/providers/steam/client.ts", true], ["test-support/runtime.ts", true], ["app/page.test.tsx", true], ["lib/value.spec.ts", true], ["drizzle/meta/0007_snapshot.json", true], ["generated/site-data.json", true], ["content/manifests/batch.json", true], [".env.local", true], [".dev.vars", true], [".npmrc", false], ["arbitrary-local-config.json", false], ["app/untracked.tsx", false]] as const)("rejects non-production input %s", (path, tracked) => expect(isProductionBuildInput(path, tracked)).toBe(false));
  it("copies only approved tracked files", async () => { const root = await mkdtemp("/private/tmp/production-inputs-"); const project = resolve(root, "project"); const build = resolve(root, "build"); await mkdir(resolve(project, "app"), { recursive: true }); await writeFile(resolve(project, "app/page.tsx"), "production"); await writeFile(resolve(project, "lib-site-fixture"), "fixture"); await writeFile(resolve(project, ".npmrc"), "credential"); try { await copyTrackedProductionInputs(project, build, ["app/page.tsx", ".npmrc"]); await expect(readFile(resolve(build, "app/page.tsx"), "utf8")).resolves.toBe("production"); await expect(readFile(resolve(build, ".npmrc"), "utf8")).rejects.toThrow(); } finally { await rm(root, { recursive: true, force: true }); } });
  it("passes only a minimal non-provider environment", () => { const environment = productionBuildEnvironment({ PATH: "/bin", HOME: "/home/operator", TWITCH_CLIENT_SECRET: "secret-canary", IMAGE_INGEST_TOKEN: "token-canary", UNKNOWN_CREDENTIAL: "credential-canary" }, "/tmp/build"); expect(environment).toMatchObject({ PATH: "/bin", HOME: "/home/operator", NODE_ENV: "production", NEXT_TELEMETRY_DISABLED: "1" }); expect(JSON.stringify(environment)).not.toMatch(/secret-canary|token-canary|credential-canary/); });
});
